"""empty message

Revision ID: 08d7d0ba989d
Revises: 7d226bf6b5bb
Create Date: 2023-03-05 03:48:25.713248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d7d0ba989d'
down_revision = '7d226bf6b5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_fullname', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_shortname', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_uraddress', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_pochtaddress', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_kpp', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_ogrn', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_director', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_osnovanie', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_bank_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_bank_bik', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_bank_rs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_bank_ks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_contact_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_contact_phone', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_contact_email', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('client_contact_email')
        batch_op.drop_column('client_contact_phone')
        batch_op.drop_column('client_contact_name')
        batch_op.drop_column('client_bank_ks')
        batch_op.drop_column('client_bank_rs')
        batch_op.drop_column('client_bank_bik')
        batch_op.drop_column('client_bank_name')
        batch_op.drop_column('client_osnovanie')
        batch_op.drop_column('client_director')
        batch_op.drop_column('client_ogrn')
        batch_op.drop_column('client_kpp')
        batch_op.drop_column('client_pochtaddress')
        batch_op.drop_column('client_uraddress')
        batch_op.drop_column('client_shortname')
        batch_op.drop_column('client_fullname')

    # ### end Alembic commands ###
