"""empty message

Revision ID: 166f5504bde3
Revises: 9750844fc3d7
Create Date: 2023-01-10 03:56:31.977792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166f5504bde3'
down_revision = '9750844fc3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventready', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventready', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
