"""empty message

Revision ID: 170fa2937f17
Revises: 224205ec18d2
Create Date: 2022-12-22 01:31:28.415110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170fa2937f17'
down_revision = '224205ec18d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enalogs',
    sa.Column('sysnalog_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['sysnalog_id'], ['systnalog.id'], )
    )
    op.create_table('eopfs',
    sa.Column('opf_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['opf_id'], ['opf.id'], )
    )
    op.create_table('etags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etags')
    op.drop_table('eopfs')
    op.drop_table('enalogs')
    # ### end Alembic commands ###
