"""empty message

Revision ID: 24fca44ee3cc
Revises: 6a1a608ee2ff
Create Date: 2022-12-18 04:53:22.931179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fca44ee3cc'
down_revision = '6a1a608ee2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_inn', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['client_inn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('client_inn')

    # ### end Alembic commands ###
