"""empty message

Revision ID: 2e13ef07325f
Revises: 3fad7f3e41a8
Create Date: 2023-02-17 01:33:42.060296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e13ef07325f'
down_revision = '3fad7f3e41a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('event_controlorgan_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('event_vidotchet_id_fkey', type_='foreignkey')
        batch_op.drop_column('controlorgan_id')
        batch_op.drop_column('vidotchet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vidotchet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('controlorgan_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('event_vidotchet_id_fkey', 'vidotchet', ['vidotchet_id'], ['id'])
        batch_op.create_foreign_key('event_controlorgan_id_fkey', 'controlorgan', ['controlorgan_id'], ['id'])

    # ### end Alembic commands ###
