"""empty message

Revision ID: 40ef52d4a526
Revises: 8862345e94d6
Create Date: 2023-03-10 05:16:12.397638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ef52d4a526'
down_revision = '8862345e94d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_event', schema=None) as batch_op:
        batch_op.drop_column('short_name')

    # ### end Alembic commands ###
