"""empty message

Revision ID: 49efc8756a92
Revises: 7134f7ffacc5
Create Date: 2022-12-13 03:02:55.425163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49efc8756a92'
down_revision = '7134f7ffacc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opfs',
    sa.Column('opf_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['opf_id'], ['opf.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opfs')
    # ### end Alembic commands ###
