"""empty message

Revision ID: 61dfbf606384
Revises: b2d74af014cf
Create Date: 2023-02-18 01:44:00.698372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dfbf606384'
down_revision = 'b2d74af014cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=True),
    sa.Column('event_data_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_event')
    # ### end Alembic commands ###
