"""empty message

Revision ID: 62aba08f25c6
Revises: 2823fb9d437d
Create Date: 2023-03-14 00:26:56.155874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62aba08f25c6'
down_revision = '2823fb9d437d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_date_created', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('company_date_created')

    # ### end Alembic commands ###
