"""empty message

Revision ID: 63cabc840384
Revises: e58aae6ac6b1
Create Date: 2023-02-20 00:13:01.227688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cabc840384'
down_revision = 'e58aae6ac6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('company_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['admin_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('company_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
