"""empty message

Revision ID: 6629759e97f4
Revises: e6dbbba0a99e
Create Date: 2023-01-10 05:36:48.112681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6629759e97f4'
down_revision = 'e6dbbba0a99e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('client_inn',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=25),
               existing_nullable=True)
        batch_op.drop_constraint('client_client_inn_key', type_='unique')
        batch_op.drop_constraint('client_client_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_unique_constraint('client_client_name_key', ['client_name'])
        batch_op.create_unique_constraint('client_client_inn_key', ['client_inn'])
        batch_op.alter_column('client_inn',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
