"""empty message

Revision ID: 77fe7a07c3ac
Revises: 2af797222c47
Create Date: 2022-12-19 03:07:56.261148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fe7a07c3ac'
down_revision = '2af797222c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_datazp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_dataavansa', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('client_dataavansa')
        batch_op.drop_column('client_datazp')

    # ### end Alembic commands ###
