"""empty message

Revision ID: 8862345e94d6
Revises: 08d7d0ba989d
Create Date: 2023-03-10 03:21:38.027712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8862345e94d6'
down_revision = '08d7d0ba989d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_zp', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_event', schema=None) as batch_op:
        batch_op.drop_column('is_zp')

    # ### end Alembic commands ###
