"""empty message

Revision ID: 9e9111ee7158
Revises: 28bd2d4e7d4e
Create Date: 2023-02-22 04:26:43.694751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9111ee7158'
down_revision = '28bd2d4e7d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('eusers')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('client_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('client_user_id_fkey', 'user', ['user_id'], ['id'])

    op.create_table('eusers',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='eusers_client_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='eusers_user_id_fkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
