"""empty message

Revision ID: b2d74af014cf
Revises: 2e13ef07325f
Create Date: 2023-02-17 02:41:59.592978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d74af014cf'
down_revision = '2e13ef07325f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('controlorgan')
    op.drop_table('vidotchet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vidotchet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vid_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vidotchet_pkey'),
    sa.UniqueConstraint('vid_name', name='vidotchet_vid_name_key')
    )
    op.create_table('controlorgan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('control_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='controlorgan_pkey'),
    sa.UniqueConstraint('control_name', name='controlorgan_control_name_key')
    )
    # ### end Alembic commands ###
