"""empty message

Revision ID: bd381ec7a0ab
Revises: e8125ced891c
Create Date: 2023-03-14 00:23:01.726495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd381ec7a0ab'
down_revision = 'e8125ced891c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_user', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('count_client', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('count_client')
        batch_op.drop_column('count_user')

    # ### end Alembic commands ###
