"""empty message

Revision ID: c9fc363f6295
Revises: 170fa2937f17
Create Date: 2022-12-25 03:30:18.273234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fc363f6295'
down_revision = '170fa2937f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlorgan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_name')
    )
    op.create_table('vidotchet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vid_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vid_name')
    )
    op.create_table('econtrolorgan',
    sa.Column('controlorgan_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['controlorgan_id'], ['controlorgan.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], )
    )
    op.create_table('evidotchet',
    sa.Column('vidotchet_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['vidotchet_id'], ['vidotchet.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidotchet')
    op.drop_table('econtrolorgan')
    op.drop_table('vidotchet')
    op.drop_table('controlorgan')
    # ### end Alembic commands ###
