"""empty message

Revision ID: d144bcc03656
Revises: c53f2b54b9dd
Create Date: 2023-01-23 03:35:13.215534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd144bcc03656'
down_revision = 'c53f2b54b9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventready', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint(None, ['status'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventready', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
