"""empty message

Revision ID: dc46c8a44b5f
Revises: 5178640cad9c
Create Date: 2023-01-06 01:21:06.268136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc46c8a44b5f'
down_revision = '5178640cad9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_data_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('event_data_end', sa.Date(), nullable=True))
        batch_op.drop_column('event_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_data', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('event_data_end')
        batch_op.drop_column('event_data_start')

    # ### end Alembic commands ###
