"""empty message

Revision ID: e0aa406f245f
Revises: f08a341c1196
Create Date: 2023-02-16 04:57:07.008896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0aa406f245f'
down_revision = 'f08a341c1196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zarplata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zarplata')
    # ### end Alembic commands ###
