"""empty message

Revision ID: e1485c6b60ca
Revises: fd880d7d0b5b
Create Date: 2023-02-10 03:05:43.663638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1485c6b60ca'
down_revision = 'fd880d7d0b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_event', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('short_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('short_name')
        batch_op.drop_column('type_event')

    # ### end Alembic commands ###
