"""empty message

Revision ID: e6dbbba0a99e
Revises: 6c3d3902fd13
Create Date: 2023-01-10 04:25:45.187780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6dbbba0a99e'
down_revision = '6c3d3902fd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventready', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eventstatus_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'eventstatus', ['eventstatus_id'], ['id'])
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventready', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('eventstatus_id')

    # ### end Alembic commands ###
