"""empty message

Revision ID: e8125ced891c
Revises: 40ef52d4a526
Create Date: 2023-03-11 05:24:22.427224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8125ced891c'
down_revision = '40ef52d4a526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_event', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_event', schema=None) as batch_op:
        batch_op.drop_column('type_event')

    # ### end Alembic commands ###
