"""empty message

Revision ID: f81835b8b464
Revises: 42ec7d945257
Create Date: 2023-02-20 00:53:42.193810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81835b8b464'
down_revision = '42ec7d945257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('client_company_id_fkey', type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('client_company_id_fkey', 'company', ['company_id'], ['id'])

    # ### end Alembic commands ###
