"""empty message

Revision ID: fd880d7d0b5b
Revises: d144bcc03656
Create Date: 2023-01-23 03:37:13.398076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd880d7d0b5b'
down_revision = 'd144bcc03656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventready', schema=None) as batch_op:
        batch_op.drop_constraint('eventready_status_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventready', schema=None) as batch_op:
        batch_op.create_unique_constraint('eventready_status_key', ['status'])

    # ### end Alembic commands ###
